services:
  db:
    container_name: postgresservice
    image: postgres:latest
    environment:
        POSTGRES_USER: damian
        POSTGRES_PASSWORD: password
        PGDATA: /data/postgres
        POSTGRES_DB: maindb
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db:

